
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version:
 - 11.3
 - 11.7
 - 12.0
 - 12.1
 - 12.2
target:
 - swiftpm
 - swiftpm-address
 - swiftpm-thread
 - swiftpm-ios
configuration:
 - Debug
 - Release

exclude:

  - xcode_version: 11.3
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.7
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.7
    target: swiftpm
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm
    configuration: Debug

  - xcode_version: 12.0
    target: swiftpm
    configuration: Release

  - xcode_version: 12.1
    target: swiftpm
    configuration: Debug

  - xcode_version: 12.1
    target: swiftpm
    configuration: Release

  - xcode_version: 12.2
    target: swiftpm
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-address
    configuration: Release

  - xcode_version: 11.7
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.7
    target: swiftpm-address
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 12.0
    target: swiftpm-address
    configuration: Release

  - xcode_version: 12.1
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 12.1
    target: swiftpm-address
    configuration: Release

  - xcode_version: 12.2
    target: swiftpm-address
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 11.7
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.7
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 12.0
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 12.1
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 12.1
    target: swiftpm-thread
    configuration: Release

  - xcode_version: 12.2
    target: swiftpm-thread
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.3
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 11.7
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 11.7
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 12.0
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 12.0
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 12.1
    target: swiftpm-ios
    configuration: Debug

  - xcode_version: 12.1
    target: swiftpm-ios
    configuration: Release

  - xcode_version: 12.2
    target: swiftpm-ios
    configuration: Debug
